title: Tomáš Matějíček
description: Blog o HTB
show_downloads: false
google_analytics: UA-3357885-16
theme: jekyll-theme-hacker

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
